### ISSUE TITLE
500 internal server error on agenda new

### ISSUE THREAD

**Issue by royfielding** [apache/whimsy#102]
I am trying to generate a new board agenda and am still getting a 500 error. Here are the access log entries. The first is a websocket while looking at the current agenda, followed by the request for /board/agenda/new responding 500 and another websocket responding 502
```
<%JSON:httpd_access%> { "time": "2020-07-16T18:36:11+0000", "clientip": "68.101.102.139", "duration": 24282820, "status": 200, "request": "/board/agenda/websocket/", "uri": "/board/agenda/websocket/", "remote_user": "-", "query_string": "", "document": "proxy:wss://localhost:34234/", "bytes": 0, "request_method": "GET", "referer": "-", "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0", "vhost": "whimsy.apache.org", "geo_country": "-", "geo_long": "-", "geo_lat": "-", "geo_coords": "-,-", "geo_city": "-", "geo_combo": "-, -" }
<%JSON:httpd_access%> { "time": "2020-07-16T18:36:35+0000", "clientip": "68.101.102.139", "duration": 361756, "status": 500, "request": "/board/agenda/new", "uri": "/board/agenda/new", "remote_user": "fielding", "query_string": "", "document": "/x1/srv/whimsy/www/board/agenda/publicnew", "bytes": 30, "request_method": "GET", "referer": "-", "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0", "vhost": "whimsy.apache.org", "geo_country": "-", "geo_long": "-", "geo_lat": "-", "geo_coords": "-,-", "geo_city": "-", "geo_combo": "-, -" }
<%JSON:httpd_access%> { "time": "2020-07-16T18:36:36+0000", "clientip": "68.101.102.139", "duration": 86914, "status": 502, "request": "/board/agenda/websocket/", "uri": "/board/agenda/websocket/", "remote_user": "-", "query_string": "", "document": "proxy:wss://localhost:34234/", "bytes": 0, "request_method": "GET", "referer": "-", "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:78.0) Gecko/20100101 Firefox/78.0", "vhost": "whimsy.apache.org", "geo_country": "-", "geo_long": "-", "geo_lat": "-", "geo_coords": "-,-", "geo_city": "-", "geo_combo": "-, -" }
```
I thought my first attempt failed because of the minutes (fixed by "https://github.com/apache/whimsy/commit/c40d21ccbbeca7e3b4e4907421853400c6e32f06") but the situation has not improved.

It looks like this is the relevant stack trace in the error_log:
```
App 6361 output: * SVN board  : /srv/svn/foundation_board
App 6361 output: * Agenda work: /srv/agenda
App 6693 output: 2020-07-16 18:36:36 - NoMethodError - undefined method `public_name' for nil:NilClass:
App 6693 output: 	/x1/srv/whimsy/lib/whimsy/asf/board.rb:131:in `for'
App 6693 output: 	(erubis:140:in `block in <top (required)>'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'
App 6693 output: 	/x1/srv/whimsy/www/board/agenda/routes.rb:550:in `block in <top (required)>'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
App 6693 output: 	/x1/srv/whimsy/lib/whimsy/asf/rack.rb:225:in `call'
App 6693 output: 	/x1/srv/whimsy/lib/whimsy/asf/rack.rb:202:in `call'
App 6693 output: 	/x1/srv/whimsy/lib/whimsy/asf/rack.rb:256:in `call'
App 6693 output: 	/x1/srv/whimsy/lib/whimsy/asf/rack.rb:81:in `call'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 6693 output: 	/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by rubys** [comment]
The problem is that the template still includes Jakarta EE Relations, for which there is no chair.

I've added some code to make the error message more useful (and actually appear in the browser window):

https://github.com/apache/whimsy/commit/ac6b728123e866f660a673b50b0099c43beaccec

If you try it now, what you would see is:

error in /srv/svn/foundation_board/templates/board_agenda.erb in: no chair found for jakartaeerelations

My hope is that this would at least give you a fighting chance to figure out what the real problem is.

**Comment by royfielding** [comment]
Thanks, that definitely helps.
