### ISSUE TITLE
rake docker:update fails

### ISSUE THREAD

**Issue by grobmeier** [apache/whimsy#157]
rake docker:update yields the following error (MacOS):

```
rake aborted!
Errno::ENOENT: No such file or directory @ apply2files - /srv/whimsy/www/docs/api
/srv/whimsy/rakefile:350:in `block in <top (required)>'
/srv/whimsy/rakefile:101:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => rdoc => www/docs/api/index.html
(See full trace by running task with --trace)
ERROR: 1
rake aborted!
Command failed with status (1): [docker-compose run  --entrypoint 'bash -c ...]
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/file_utils.rb:57:in `sh'
/Users/cy/Development/apache-whimsy/whimsy/Rakefile:372:in `block (2 levels) in <top (required)>'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/cy/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/cy/.rvm/rubies/ruby-2.6.3/bin/rake:23:in `load'
/Users/cy/.rvm/rubies/ruby-2.6.3/bin/rake:23:in `<main>'
```

**Comment by sebbASF** [comment]
What did you do before this?

**Comment by grobmeier** [comment]
I did:

```
git clone git@github.com:apache/whimsy.git
cd whimsy
rake docker:update
```

as per these docs:
https://github.com/apache/whimsy/blob/master/DOCKER.md

**Comment by sebbASF** [comment]
Please pull and try again

**Comment by grobmeier** [comment]
Works like a charm, thanks @sebbASF
