### ISSUE TITLE
Internal Server Error on committee page

### ISSUE THREAD

**Issue by tisonkun** [apache/whimsy#231]
https://whimsy.apache.org/roster/committee/

```
#<NameError: undefined local variable or method `td'>
  /x1/srv/whimsy/www/roster/views/committees.html.rb:86:in `block (6 levels) in _evaluate'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:67:in `block (5 levels) in _evaluate'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:59:in `each'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:59:in `block (4 levels) in _evaluate'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:57:in `block (3 levels) in _evaluate'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:47:in `block (2 levels) in _evaluate'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:195:in `block (3 levels) in _whimsy_body'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:179:in `block (2 levels) in _whimsy_body'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:178:in `block in _whimsy_body'
  /x1/srv/whimsy/lib/whimsy/asf/themes.rb:135:in `_whimsy_body'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:8:in `block in _evaluate'
  /x1/srv/whimsy/www/roster/views/committees.html.rb:5:in `_evaluate'
  /x1/srv/whimsy/www/roster/main.rb:64:in `block in <top (required)>'
  /x1/srv/whimsy/lib/whimsy/asf/rack.rb:225:in `call'
  /x1/srv/whimsy/lib/whimsy/asf/rack.rb:51:in `call'
  /x1/srv/whimsy/lib/whimsy/asf/rack.rb:202:in `call'
  /x1/srv/whimsy/lib/whimsy/asf/rack.rb:256:in `call'
  /var/lib/gems/2.7.0/gems/passenger-6.0.19/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
  /var/lib/gems/2.7.0/gems/passenger-6.0.19/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
  /var/lib/gems/2.7.0/gems/passenger-6.0.19/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  /var/lib/gems/2.7.0/gems/passenger-6.0.19/src/ruby_supportlib/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
  /var/lib/gems/2.7.0/gems/passenger-6.0.19/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by tisonkun** [comment]
Fixed by https://github.com/apache/whimsy/commit/39c7f323d9a8f047e07790a74a23ad4ed38e7d7b
